export const CartActionTypes = {
  TOGGLE_CART_MENU: "TOGGLE_CART_MENU",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM: "CLEAR_ITEM",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  CONFIRM_DELETE: "CONFIRM_DELETE",
};
